[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.0"
edition = "2021"
authors = ["Elli Beres <elliberes@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.h
[dependencies]
rand = "0.8"